source $HOME/.vim/general/settings.vim
source $HOME/.vim/general/commands.vim
source $HOME/.vim/general/keys.vim

source $HOME/.vim/vim-plug/plugins.vim
source $HOME/.vim/plugin-settings/settings.vim

source $HOME/.vim/keys/windows.vim
source $HOME/.vim/keys/buffers.vim
" source $HOME/.vim/keys/tabs.vim
source $HOME/.vim/keys/coc.vim
source $HOME/.vim/keys/floaterm.vim

source $HOME/.vim/autocmds/general.vim
source $HOME/.vim/autocmds/ftspecific.vim

colorscheme molokai
